apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus
spec:
  ports:
    - name: http
      port: 9093
      protocol: TCP
      targetPort: 9093
  type: "ClusterIP"
  selector:
    app: alertmanager