apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: monitoring
spec:
  selector:
    matchLabels:
      app: hello
  namespaceSelector:
    any: true
  endpoints:
  - port: kubelet
    interval: 30s