apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: cluster-monitoring
spec:
  podMetricsEndpoints:
    - port: kubelet
  podMetricsSelectors:
    - namespaceSelector: {}