apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: helloworld-gke
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-gke
  endpoints:
  - port: metrics
    interval: 30s